---
- name: Configure OPS445 CentOS 7.x VM
  hosts: jkwok
  user: student
  become: yes
  vars:
    seneca_id: vishesh1
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tasks:

    - name: Ensure Apache is updated
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Remove tree package
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create user with sudo access
      user:
        name: "{{ seneca_id }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        state: present
        create_home: yes

    - name: Add SSH public key to new user
      authorized_key:
        user: "{{ seneca_id }}"
        key: "{{ ssh_pub_key }}"

    - name: Create lab directories
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ range(1, 9)|list }}"

